services:
  frontend:
    image: yinyaodebaoyea/libbook-web:latest
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - libbook-net

  backend:
    image: yinyaodebaoyea/libbook-api:latest
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - libbook-net

  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - libbook-db-data:/var/lib/postgresql/data
    networks:
      - libbook-net

volumes:
  libbook-db-data:

networks:
  libbook-net:
